### ISSUE TITLE
documentation myhtml_tree_parse_flags

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#58]
any documentation about myhtml_tree_parse_flags?
is MyHTML_TREE_PARSE_FLAGS_WITHOUT_BUILD_TREE - sax parser? how to use it?
what is MyHTML_TREE_PARSE_FLAGS_WITHOUT_PROCESS_TOKEN?

**Comment by lexborisov** [comment]
Please, in English or send me an email lex.borisov@gmail.com

MyHTML_TREE_PARSE_FLAGS_WITHOUT_BUILD_TREE — the Tree is not created at all, tokens are processed (processed text, etc.)
MyHTML_TREE_PARSE_FLAGS_WITHOUT_PROCESS_TOKEN — Tokens are not processed and the Tree is not created

This needs for callbacks. See example [tokenizer_colorize](https://github.com/lexborisov/myhtml/blob/master/examples/tokenizer_colorize_high_level.c)

**Comment by kostya** [comment]
in tokenizer_colorize there is no MyHTML_TREE_PARSE_FLAGS_WITHOUT_PROCESS_TOKEN, is it set by default when call myhtml_callback_before_token_done_set, or in this example just used callback, and tree also builded?

**Comment by lexborisov** [comment]
Oh, sorry, 
but you can add the flag MyHTML_TREE_PARSE_FLAGS_WITHOUT_BUILD_TREE in the [example](https://github.com/lexborisov/myhtml/blob/master/examples/tokenizer_colorize_high_level.c) and the tree will not be created. 
This does not affect for the example because the tree it does not need. But without the tree some tags will be not handled properly: svg, math.

That is, there are times when the tree does not need. Then you can put on callbacks for tokens and handle them yourself. As shown in [example](https://github.com/lexborisov/myhtml/blob/master/examples/tokenizer_colorize_high_level.c)

**Comment by kostya** [comment]
thanks, thats nice. i don't need svg or math, disable build tree should save much memory, and also be faster

**Comment by kostya** [comment]
btw, what include token processing?

**Comment by lexborisov** [comment]
Yes, everything you listed. Nothing else.

**Comment by kostya** [comment]
in the example used incoming_buffer, but how to get processed tag_names, tag_texts, attributes?
is there some outcome_buffer?

**Comment by lexborisov** [comment]
```C
    // set callback after token done
    myhtml_callback_after_token_done_set(tree, mycallback_after_token_done, NULL);
```

```C
void * mycallback_after_token_done(myhtml_tree_t* tree, myhtml_token_node_t* token, void* ctx)
{
    myhtml_tag_id_t tag_id = myhtml_token_node_tag_id(token);

    size_t length;
    const char *text = myhtml_token_node_text(token, &length);

    /* and other */
}
```

Please!!! see [MyHTML_TOKEN_NODE in api.h](https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h#L1723) and [MyHTML_CALLBACK](https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h#L2493)
