### ISSUE TITLE
[bug] myhtml_get_nodes_by_tag_id in 2.0.0 get more nodes, than in 1.0.4

### ISSUE THREAD

**Issue by kostya** [lexborisov/myhtml#86]
```crystal
require "myhtml"

str = File.read(filename, "UTF-8", invalid: :skip)
parser = Myhtml::Parser.new(str)

parser.nodes(:a).each do |node|
  p node.attribute_by("href")
end
```

for 1.0.4 gets 52 links, for 2.0.0 gets 56 links.
for page https://www.dropbox.com/s/fg6pldruyiap3la/test_23.html

2.0.0 gets 3 links for this url, 1.0.4 only 2 links:
```
...
"http://yandas.ru/"
"http://yandas.ru/"
"http://yandas.ru/"
...
```
on page i see only 2 this links with "http://yandas.ru/".

btw, хтмл довольно кривущий, возможно и не баг.

**Comment by lexborisov** [comment]
It is not a bug. Everything is fine.
```HTML
<noscript><a href=http://yandas.ru/ target=_blank><img src="http://yandas.ru/img.php?id=20942" border=0 alt="Каталог сайтов" width='88' height='31'></a></noscript>
</a>
```

Because of the tag ```</a>``` do not close anything and it turns on [the adoption agency algorithm](https://html.spec.whatwg.org/multipage/syntax.html#adoption-agency-algorithm). 

If you set ```tree->flags |= MyHTML_TREE_FLAGS_SCRIPT``` flag before start parsing (parsing will think that he has js)  then it will not be processed ```<noscript>``` tokens and then the "extra" elements disappear.

In the previous version did not take recovered items, that was not correct (wrong logically). Now everything is working as it should.

Try disable JS in your modern browser and see it also creates additional elements, but if JS is on ```<noscript>``` parsed as text.

**Comment by kostya** [comment]
yes, in browser the same, little strange, ok.

**Comment by kostya** [comment]
can you please push new release, because for wrapper, when install it, faster to download from releases page, than from git.

**Comment by lexborisov** [comment]
Yes, soon. I want to include validation of this release.
