### ISSUE TITLE
myhtml_tag_id_t

### ISSUE THREAD

**Issue by stasoid** [lexborisov/myhtml#97]
I propose to change `myhtml_tag_id_t` to see tag name of a tree node in Visual Studio debugger watch window.
In include/myhtml/myosi.h
change
`typedef size_t myhtml_tag_id_t;`
to
`typedef enum myhtml_tags myhtml_tag_id_t;`

I am aware that such typedef creates wrong impression that `myhtml_tag_id_t` can only have values of the `enum myhtml_tags`, but having it `size_t` is equally confusing (I think) and doesn't have abovementioned benefit (to see tag names at least for known tags).

**Comment by lexborisov** [comment]
Hi!
The problem is that the number of tags can be "infinite".

For example:
```HTML
<div><la><blah><tagoftag>
```
`<div>` — MyHTML_TAG_DIV (0x02a)
`<la>` — MyHTML_TAG_LAST_ENTRY + 1 (0x0fd)
`<blah>` — MyHTML_TAG_LAST_ENTRY + 2 (0x0fe)
`<tagoftag>` — MyHTML_TAG_LAST_ENTRY + 3 (0x0ff)

For get name of tag `exists` or `not exists` in `myhtml_tags` use function `myhtml_tag_name_by_id`.

In theory, nothing bad will happen if I change `size_t` to `enum` for myhtml_tag_id_t, but [see C99 spec](http://www.open-std.org/JTC1/SC22/WG14/www/docs/n1256.pdf) `6.7.2.2 Enumeration specifiers`

> Each enumerated type shall be compatible with char, a signed integer type, or an unsigned integer type. The choice of type is implementation-defined, but shall be capable of representing the values of all the members of the enumeration.

The compiler is free to choose the actual type used.

**Comment by stasoid** [comment]
Got it, thank you
